start "PubSub" /D "PubSub\bin\Debug" "PubSub.exe"
start "NMS" /D "NMS\bin\Debug" "NMS.exe"
start "CalculationEngine" /D "CalculationEngine\bin\Debug" "CalculationEngine.exe"
start "SCADA" /D "SCADA\bin\Debug" "SCADA.exe"
start "SCADASim" /D "SCADASim\bin\Debug" "SCADASim.exe"
start "GUI" /D "GUI\bin\Debug" "GUI.exe"